Beta changes on everything except for experimental roles/more settings
0xDrMoe/TOHRE-Code pull request #49
Opened 2023-10-04 04:36 UTC by Pyro0TV

moe do the rest im bored

if it broke dont dm me

2023-10-04 05:04 UTC, 0xDrMoe requested changes

2023-10-04 05:04 UTC, 0xDrMoe commented on options/Addons/Helpful/Overclocked.md
Missing description

2023-10-04 05:04 UTC, 0xDrMoe commented on options/Impostors/Concealing/Vampire.md
Missing a few lines of information, my friend

2023-10-04 18:15 UTC, 0xDrMoe commented
why was this closed

2023-10-06 08:02 UTC, 0xDrMoe approved these changes

2023-10-06 18:14 UTC, Ultradragon005 commented
this shit is crazyyyy

2023-10-06 19:42 UTC, merged