Update FAQ.md
0xDrMoe/TOHRE-Code pull request #50
Opened 2023-10-08 01:52 UTC by KingJacob105

Various grammar corrections and entry modifications
- Seleneous <3

2023-10-11 16:16 UTC, Pyro0TV commented
I like this because it doesn't overwrite anything I'm actively doing

2023-10-12 06:30 UTC, 0xDrMoe commented on FAQ.md
> +The game will end suddenly if there are still impostors alive and the victory conditions of the neutrals are not met. Two other may include possibilities:
two other may include?

2023-10-12 06:31 UTC, 0xDrMoe requested changes
two other may include?

2023-10-19 14:10 UTC, pyrosliced commented
I've since updated the FAQ as this was left quiet, close this perhaps?

2023-10-31 23:02 UTC, closed without merging